// AI report → PDF, generated by Apex / Eclipse Softworks. jsPDF is imported
// dynamically so it never runs during SSR.

const BRAND = [79, 70, 229];
const INK = [30, 41, 59];
const MUT = [100, 116, 139];
const LINE = [226, 232, 240];
const SOFT = [238, 240, 254];

const METRICS = [
  ["Completed tasks", "156", "+18%"],
  ["Commits", "342", "+16%"],
  ["PRs merged", "48", "+14%"],
  ["Code reviews", "96", "+20%"],
];
const RISKS = [
  ["Mobile App Launch", "Apex v2.1", "Jun 24", "High"],
  ["Analytics Module", "Apex v2.1", "Jun 30", "Medium"],
  ["API Gateway v2", "Platform Core", "Jun 28", "Medium"],
  ["Security Audit", "Platform Core", "Jul 02", "Low"],
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export async function generateReportPdf(title = "Apex Report", opts = {}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const L = 48, R = W - 48;
  const date = opts.date || new Date().toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric" });

  // header
  doc.setFillColor(...BRAND); doc.rect(0, 0, W, 7, "F");
  let y = 64;
  doc.setTextColor(...INK); doc.setFont("helvetica", "bold"); doc.setFontSize(21); doc.text("Apex", L, y);
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(...MUT); doc.text("by Eclipse Softworks", L, y + 16);
  doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(...BRAND); doc.text("AI REPORT", R, y, { align: "right" });
  doc.setFont("helvetica", "normal"); doc.setFontSize(9.5); doc.setTextColor(...MUT); doc.text(date, R, y + 16, { align: "right" });

  y += 40; doc.setDrawColor(...LINE); doc.line(L, y, R, y); y += 30;

  // title block
  doc.setTextColor(...INK); doc.setFont("helvetica", "bold"); doc.setFontSize(18); doc.text(title, L, y);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9.5); doc.setTextColor(...MUT);
  doc.text("Eclipse Softworks workspace  ·  generated by Apex AI", L, y + 16);
  y += 46;

  const section = (label) => {
    doc.setFont("helvetica", "bold"); doc.setFontSize(8.5); doc.setTextColor(...BRAND);
    doc.text(label.toUpperCase(), L, y); y += 8;
    doc.setDrawColor(...LINE); doc.line(L, y, R, y); y += 18;
  };

  // executive summary
  section("Executive summary");
  doc.setFont("helvetica", "normal"); doc.setFontSize(10.5); doc.setTextColor(...INK);
  const summary = "Across 24 active projects, 16 are on track, 6 are at risk and 2 are overdue. Weekly velocity is up 12% with 156 tasks completed and 342 commits merged. Apex v2.1 remains the primary risk at 72% likelihood of delay, driven by delayed dependencies on the Mobile App Launch milestone.";
  const lines = doc.splitTextToSize(summary, R - L);
  doc.text(lines, L, y); y += lines.length * 15 + 18;

  // key metrics
  section("Key metrics (this week)");
  const colW = (R - L) / 4;
  METRICS.forEach((m, i) => {
    const x = L + i * colW;
    doc.setFillColor(...SOFT); doc.roundedRect(x, y, colW - 10, 58, 6, 6, "F");
    doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.setTextColor(...MUT); doc.text(m[0], x + 12, y + 18);
    doc.setFont("helvetica", "bold"); doc.setFontSize(17); doc.setTextColor(...INK); doc.text(m[1], x + 12, y + 40);
    doc.setFont("helvetica", "bold"); doc.setFontSize(8.5); doc.setTextColor(22, 163, 74); doc.text(m[2], x + 12, y + 52);
  });
  y += 80;

  // milestones at risk
  section("Milestones at risk");
  const cols = [L, L + 200, L + 330, R - 60];
  doc.setFont("helvetica", "bold"); doc.setFontSize(8.5); doc.setTextColor(...MUT);
  ["MILESTONE", "PROJECT", "DUE", "RISK"].forEach((h, i) => doc.text(h, cols[i], y));
  y += 6; doc.setDrawColor(...LINE); doc.line(L, y, R, y); y += 16;
  doc.setFontSize(10);
  RISKS.forEach((r) => {
    doc.setFont("helvetica", "bold"); doc.setTextColor(...INK); doc.text(r[0], cols[0], y);
    doc.setFont("helvetica", "normal"); doc.setTextColor(...MUT); doc.text(r[1], cols[1], y); doc.text(r[2], cols[2], y);
    const c = r[3] === "High" ? [220, 38, 38] : r[3] === "Medium" ? [180, 83, 9] : [22, 163, 74];
    doc.setFont("helvetica", "bold"); doc.setTextColor(...c); doc.text(r[3], cols[3], y);
    y += 18; doc.setDrawColor(...LINE); doc.line(L, y - 6, R, y - 6);
  });

  // footer
  const H = doc.internal.pageSize.getHeight();
  doc.setDrawColor(...LINE); doc.line(L, H - 56, R, H - 56);
  doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.setTextColor(...MUT);
  doc.text("Apex · Eclipse Softworks (Pty) Ltd · Sandton, South Africa", L, H - 38);
  doc.text("Confidential — generated by Apex AI", R, H - 38, { align: "right" });

  doc.save(`Apex-${slug(title) || "report"}.pdf`);
}
